<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Post
 *
 * @method static \Illuminate\Database\Eloquent\Builder|Post newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Post newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Post query()
 * @mixin \Eloquent
 * @property int $id
 * @property string $title
 * @property string $content
 * @property string $images
 * @property int $user_id
 * @property int $like
 * @property int $comments
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereComments($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereContent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereImages($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereLike($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereUserId($value)
 */
class Post extends Model
{
    use HasFactory;

    public User $user;
    protected $fillable = [
        'user_id',
        'title',
        'content',
        'images',
        'like',
        'comments'
    ];



    public function setUp($attr)
    {
        $this->fill($attr);
    }

    public function toArray(): array
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

//    public function __construct(string $title, string $content, string $images, int $user_id,$like,$comments)
//    {
//        $this->fill([
//            'user_id' => $user_id,
//            'title' => $title,
//            'content' => $content,
//            'images' => $images,
//            'like' => $like,
//            'comments' => $comments
//        ]);
//    }



}
